api_version: 1
entrypoint: "gunicorn -b:$PORT main:app"
env: flex
handlers: 
  - 
    static_dir: static
    url: /static
  - 
    script: app.app
    url: /.*
runtime: python
runtime_config:
    python_version: 3
threadsafe: true